version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
